import React from "react";
import Anime from "react-anime";
import logo from "../logo.svg";
import BetAmount from "./BetAmount";

type RouletteProps = {
  title: string;
};

function Roulette({ title }: RouletteProps) {
  return (
    <div className="Roulette shadow-lg rounded">
      <div className="p-5 rounded-t bg-navyLight-400">
        <div className="text-navy-200">Bet Amount</div>
        <BetAmount amount={3} />
      </div>
      <div className="p-5 rounded-b bg-black bg-opacity-60 text-white">
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here... Animation goes here...
        Animation goes here... Animation goes here...
      </div>
    </div>
  );
}

export default Roulette;
